name: Push
on: [push]
jobs:
  Setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm install --no-save c8
      - run: npm run postinstall
      - run: echo $REF
        env:
          REF: ${{ github.ref }}
