name: Test
on: [push, pull_request]
jobs:
  Setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: echo $REF
        env:
          REF: ${{ github.ref }}
      - run: echo $EnvName
        env:
          EnvName: test-${{ github.event.number }}
